### PR TITLE
apply formatting

### PR DESCRIPTION
**Pull request by danieleades**
fixes the formatting, again

looks like something got messed up in all that merging

### CODE REVIEW

**Comment by danieleades** [comment]
@jhelovuo how are you applying formatting in your commits? Since you're using nightly-only rustfmt config, i assume you're using `cargo +nightly fmt`?

**Comment by jhelovuo** [comment]
> @jhelovuo how are you applying formatting in your commits? Since you're using nightly-only rustfmt config, i assume you're using `cargo +nightly fmt`?

I am mostly not appying formatting, since the main development is done using stable tooling. Please change rustfmt config to use stable.

**Comment by danieleades** [comment]
> I am mostly not appying formatting, since the main development is done using stable tooling. Please change rustfmt config to use stable.

Can do. That will involve removing most of the config.

Is there a reason you can't develop with stable and format with nightly? I think that's a reasonably common way to go

**Comment by jhelovuo** [comment]
> 
> Is there a reason you can't develop with stable and format with nightly? I think that's a reasonably common way to go

Not really. I just never considered mixing stable and nightly that way. But if it is a common thing to do, then I suppose it would work just fine.

So no need to revert the rustfmt config to stable. Let's go with nightly channel in formatting.

**Pull request merged**
