### PR TITLE
Refactor/upper case acronyms

### PR DESCRIPTION
**Pull request by danieleades**
use correct enum capitalisation convention

### CODE REVIEW

**Comment by jhelovuo** [comment]
Incorrect (all-caps) capitalisation is intentionally used because the DDS spec does so.
It is used to hint that this is the same thing as in the spec, e.g. SHARED vs EXCLUSIVE.

**Comment by danieleades** [comment]
@jhelovuo it looks like these enums aren't exposed in the public API. Is it just for internal documentation purposes?

**Comment by jhelovuo** [comment]
It is for documentation purposes, both internal and external. If these were changed to Rust convention, we would need to add documentation mapping the constants and enums to the corresponding DDS spec entities.

**Comment by danieleades** [comment]
> It is for documentation purposes, both internal and external. If these were changed to Rust convention, we would need to add documentation mapping the constants and enums to the corresponding DDS spec entities.

no problem. is that the case for every enum in this pull request?

rather than changing to use the correct convention, it's also possible to whitelist the specific cases to prevent the compiler/linters complaining. I can do that instead.

**Comment by danieleades** [comment]
while i've got you, are the following compiler flags for similar purposes?

```rust
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
```
this seems at odds with this line from the README-

>We have tried to translate the key ideas of the DDS application interface to Rust concepts, but also follow Rust conventions

**Comment by jhelovuo** [comment]
On second thought, maybe it is better to accept this change. There are many more names from the standard specifications, and those are converted Rust naming conventions. And yes, those seem to be internal names anyway.

**Comment by jhelovuo** [comment]
Those compilation flags suppressing warnings in lib.rs should be moved to smaller scope. 

Especailly dead code should be handled wherever it occurs. There are good reasons to have dead code around, for example, as placeholders for DDS features that are not yet implemented, but that should be marked wherever such declarations are made, not globally.

**Pull request merged**
