### PR TITLE
impl find_topic for DomainParticipant

### PR DESCRIPTION
**Pull request by kczimm**
Attempting to implement the find_topic method discussed in #9. I'm looking for advice because I'm unsure of several things.

- I changed the return type to be `Result<Option<Topic>>` because I imagine the `Topic` name may not exist. I do not know if this is correct or acceptable.
- It's unclear how `DomainParticipant_Inner` can create a `Topic` without a reference to `DomainParticipantWeak`, as suggested by the method `create_topic`, so I added an argument for such reference. I do not know if this is correct or acceptable.
- I basically found myself constructing a `QosPolicies` for `TopicBuiltinTopicData` so I just went ahead and implemented the `HasQoSPolicy` trait for it. I do not know if this is acceptable.
- I see the repo has a `rustfmt.toml` file for formatting so I assume that it is desirable to have the files formatted using those rules, however, the two files I edited for this PR had many formatting changes. If this is unacceptable and I can revert the formatting changes.

### CODE REVIEW

**Comment by kczimm** [comment]
I'm also looking for advice on how I would go about testing this, at some point.

**Comment by jhelovuo** [comment]
> Attempting to implement the find_topic method discussed in #9. I'm looking for advice because I'm unsure of several things.
> 
> * I changed the return type to be `Result<Option<Topic>>` because I imagine the `Topic` name may not exist. I do not know if this is correct or acceptable.

Yes, this is correct. See [this comment](https://github.com/jhelovuo/RustDDS/blob/master/src/dds/values/result.rs#L19)


> * It's unclear how `DomainParticipant_Inner` can create a `Topic` without a reference to `DomainParticipantWeak`, as suggested by the method `create_topic`, so I added an argument for such reference. I do not know if this is correct or acceptable.

Yes, you can and should follow the logic of `create_topic`. There is a `create_topic` method in `DomainParticipant`, which just calls `create_topic` in DomainParticipant_Disc , which again calls `create_topic` in `DomainParticipant_Inner`, which does the actual work. You should use similar hierarchy of wrappers for `find_topic`. The reason for this stack of wrappers is that we have a background RTPS/discovery thread that needs access to DomainParticipant, and all of this has to be dropped on exit in some sensible order.

> * I basically found myself constructing a `QosPolicies` for `TopicBuiltinTopicData` so I just went ahead and implemented the `HasQoSPolicy` trait for it. I do not know if this is acceptable.
> * I see the repo has a `rustfmt.toml` file for formatting so I assume that it is desirable to have the files formatted using those rules, however, the two files I edited for this PR had many formatting changes. If this is unacceptable and I can revert the formatting changes.

Clarifying formatting changes are welcome. However, since you have so many of them, please separate them in a  commit or merge request of their own, and indicate in the commit log message that this is code formatting changes only, no functionality changes. That makes functional change commits much easier to read.

**Comment by jhelovuo** [comment]
> I'm also looking for advice on how I would go about testing this, at some point.

You should set up two test programs: One test fixture and one test subject. The test fixure could be RustDDS or some other DDS implementation. It should be set up to publish (or subscribe) some topic. The test subject would be RustDDS attempting to use the `find_topic` method to get a `Topic` object (the topic published by the fixture), and then use that to set up communication with the test fixture.

**Comment by kczimm** [comment]
I'm going to close in favor of a new PR to separate formatting from functional change commits. Thanks @jhelovuo for your feedback and I hope to carry on the discussion in a new PR.

**Pull request closed without merging**
