### PR TITLE
refactor the 'endpoint' trait

### LINKED ISSUE #129: Useless Endpoints?
There is a bunch of things that seem completely useless:
* trait Endpoint
* consequently, its implementations
* EndpointAttributes fields in Writer and Reader

These should be removed.

### PR DESCRIPTION
**Pull request by danieleades**
closes #129

### CODE REVIEW

**Comment by jhelovuo** [comment]
This is a neat refactor, but is this entire trait really useful at all?

I know it is specified as a class in the RTPS specification, Section 8.2.7, but it seems to just group some data that is common between Reader and Writer. AFAIK it does not actually introduce any interface or functionality.

My suggestion to redesign Endpoint in RustDDS:

* Make it a struct instead, and include that into both Reader and Writer, if that seems useful, OR
* remove it altogether.

**Comment by danieleades** [comment]
> This is a neat refactor, but is this entire trait really useful at all?
> 
> I know it is specified as a class in the RTPS specification, Section 8.2.7, but it seems to just group some data that is common between Reader and Writer. AFAIK it does not actually introduce any interface or functionality.
> 
> My suggestion to redesign Endpoint in RustDDS:
> 
> * Make it a struct instead, and include that into both Reader and Writer, if that seems useful, OR
> * remove it altogether.

you were right- the trait's methods don't appear to have been used anywhere, so it could simply be removed.

the best PRs are the ones that remove code, instead of adding it ;)

**Comment by jhelovuo** [comment]
Right. How about `EndpointAttributes` ?

**Comment by danieleades** [comment]
> Right. How about `EndpointAttributes` ?

you were right- it's not used anywhere.

can't wait to get rid of that `#[allow(dead_code)]` attribute ;)

**Comment by jhelovuo** [comment]
Thanks. This was yet another good cleanup.

**Pull request merged**
